
# RULER:
  # tasks: ["cwe", "fwe", "niah_multikey_1", "niah_multikey_2", "niah_multikey_3", "niah_multiquery", "niah_multivalue", "niah_single_1", "niah_single_2", "niah_single_3", "qa_1", "qa_2", "vt"]
  # length: [4096,8192,16384,32768,65536,131072]
  # num_samples: 200

# LooGLE:
#   tasks: ["longdep_qa","longdep_summarization"]

# LongBench:
#   tasks: ["narrativeqa", "qasper", "multifieldqa_en", "multifieldqa_zh", "hotpotqa", "2wikimqa", "musique", "dureader", "gov_report", "qmsum", "multi_news", "vcsum", "trec", "triviaqa", "samsum", "lsht", "passage_count", "passage_retrieval_en", "passage_retrieval_zh", "lcc", "repobench-p","qasper_e", "multifieldqa_en_e", "hotpotqa_e", "2wikimqa_e", "gov_report_e", "multi_news_e", "trec_e", "triviaqa_e", "samsum_e", "passage_count_e", "passage_retrieval_en_e", "lcc_e", "repobench-p_e"]

# L_CiteEval:
#   tasks: ['L-CiteEval-Length_narrativeqa', 'L-CiteEval-Length_locomo', 'L-CiteEval-Length_hotpotqa', 'L-CiteEval-Length_gov_report', 'L-CiteEval-Length_counting_stars', 'L-CiteEval-Hardness_narrativeqa', 'L-CiteEval-Hardness_locomo', 'L-CiteEval-Hardness_hotpotqa', 'L-CiteEval-Hardness_gov_report', 'L-CiteEval-Hardness_counting_stars', 'L-CiteEval-Data_qmsum', 'L-CiteEval-Data_niah', 'L-CiteEval-Data_natural_questions', 'L-CiteEval-Data_narrativeqa', 'L-CiteEval-Data_multi_news', 'L-CiteEval-Data_locomo', 'L-CiteEval-Data_hotpotqa', 'L-CiteEval-Data_gov_report', 'L-CiteEval-Data_dialsim', 'L-CiteEval-Data_counting_stars', 'L-CiteEval-Data_2wikimultihopqa']

# Counting_Stars:
#   tasks: ["counting_stars_en_reasoning","counting_stars_en_searching","counting_stars_zh_reasoning","counting_stars_zh_searching"]

RULER_1:
  tasks: ["niah_multikey_1", "niah_multikey_2", "niah_multikey_3", "niah_multivalue", "niah_single_3", "vt"]
  length: [4096,8192,16384,32768,65536,131072]
  num_samples: 100