L-CiteEval-Data_2wikimultihopqa:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_2wikimultihopqa.json
  postprocess_task: null
  task_name: L-CiteEval-Data_2wikimultihopqa
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_counting_stars:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params1.json
  metric:
    l_cite_eavl_counting_stars_cite:
      evaluation:
        type: l_cite_eavl_counting_stars_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_counting_stars.json
  postprocess_task: null
  task_name: L-CiteEval-Data_counting_stars
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_dialsim:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_dialsim.json
  postprocess_task: null
  task_name: L-CiteEval-Data_dialsim
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_gov_report:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params3.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_gov_report.json
  postprocess_task: null
  task_name: L-CiteEval-Data_gov_report
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_hotpotqa:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_hotpotqa.json
  postprocess_task: null
  task_name: L-CiteEval-Data_hotpotqa
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_locomo:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_locomo.json
  postprocess_task: null
  task_name: L-CiteEval-Data_locomo
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_multi_news:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params3.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_multi_news.json
  postprocess_task: null
  task_name: L-CiteEval-Data_multi_news
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_narrativeqa:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_narrativeqa.json
  postprocess_task: null
  task_name: L-CiteEval-Data_narrativeqa
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_natural_questions:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params2.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_natural_questions.json
  postprocess_task: null
  task_name: L-CiteEval-Data_natural_questions
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_niah:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params1.json
  metric:
    l_cite_eavl_niah_cite:
      evaluation:
        type: l_cite_eavl_niah_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_niah.json
  postprocess_task: null
  task_name: L-CiteEval-Data_niah
  transform: ./dataset/utils/transform/L-CiteEval.py
L-CiteEval-Data_qmsum:
  description: null
  fewshot: 0
  generate:
    method: generate
    params: ./dataset/utils/llm-params/L-CiteEval_llm_params3.json
  metric:
    l_cite_eavl_cite:
      evaluation:
        type: l_cite_eavl_cite
  path: ./dataset/Factuality/data/L-CiteEval-Data_qmsum.json
  postprocess_task: null
  task_name: L-CiteEval-Data_qmsum
  transform: ./dataset/utils/transform/L-CiteEval.py
